name: Build and Push Hyperswitch

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    env:
          DOCKER_BUILDKIT: 1
          BUILDKIT_STEP_LOG_MAX_SIZE: 10485760
          BUILDKIT_STEP_LOG_MAX_SPEED: 10485760

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. NEW: Clean up the runner to maximize disk space (Hyperswitch builds are huge)
      - name: Maximize Build Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
      - name: Set up Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          provenance: false
          sbom: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hyperswitch-router:gobibuy
          cache-from: type=gha
          cache-to: type=gha,mode=min
          build-args:
            RUSTFLAGS=-C debuginfo=0 -C codegen-units=1
            CARGO_NET_GIT_FETCH_WITH_CLI=true
            CARGO_BUILD_JOBS=1
            CARGO_INCREMENTAL=0
